name: Deploy Laravel to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  # ---------------------------
  # JOB 1: Construir aplicaci√≥n
  # ---------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, bcmath, intl, sqlite3, zip, exif, pcntl
          tools: composer

      - name: Composer install (production)
        run: composer install --optimize-autoloader --no-dev --no-interaction --prefer-dist

      - name: Laravel + .env + Azure fixes
        run: |
          cp .env.example .env

          sed -i 's/APP_ENV=.*/APP_ENV=production/' .env
          sed -i 's/APP_DEBUG=.*/APP_DEBUG=false/' .env
          sed -i 's|APP_URL=.*|APP_URL=https://proyect1-ftf5fyh2efhka3ec.westus-01.azurewebsites.net/|' .env

          php artisan key:generate --force
          php artisan storage:link || true
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          mkdir -p storage/framework/{cache/data,sessions,views}
          mkdir -p storage/logs
          chmod -R 777 storage bootstrap/cache || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  # ---------------------------
  # JOB 2: Deploy a Azure
  # ---------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build   # <-- ESTE ES IMPORTANTE

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'proyect1'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_394BA62917D94783902A95C258AC480B }}
